source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'pg'
gem 'puma', '~> 3.7'
gem 'rails', '~> 5.1.4'

gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'haml-rails', '~> 1.0'
gem 'therubyracer', platforms: :ruby

gem 'devise'
gem 'simple_token_authentication', '~> 1.0'
gem "paranoia", "~> 2.2"

gem 'figaro'

gem 'mina', '~> 0.3.8'
gem 'mina-tail', require: false
gem 'mina-puma', require: false
gem 'mina-multistage', require: false

gem 'rollbar'

group :development, :test do
  gem 'pry-rails'
end

group :development do
  gem 'rubocop', require: false

  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
